PROGRAM=SmartHome
#ESPPORT ?= /dev/tty.SLAB_USBtoUART
#ESPPORT ?= /dev/tty.wchusbserial1410
ESPPORT ?= /dev/tty.SLAB_USBtoUART
#ESPPORT ?= /dev/tty.usbserial-A9M9DV3R
ESPBAUD ?= 921600
#ESPBAUD ?= 115200
FLASH_MODE ?= dout
EXTRA_COMPONENTS=/Users/tranxuan/Documents/Workspace/SmartHome/SmartHome/http_client_ota /Users/tranxuan/Documents/Workspace/SmartHome/SmartHome/mbedtls /Users/tranxuan/Documents/Workspace/SmartHome/SmartHome/paho_mqtt_c /Users/tranxuan/Documents/Workspace/SmartHome/SmartHome/rboot-ota /Users/tranxuan/Documents/Workspace/SmartHome/SmartHome/dhcpserver
#extras/paho_mqtt_c
include /Users/tranxuan/Documents/Workspace/00_Lib/esp-open-rtos/common.mk


